security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    sso_customer:
      id: App\Security\AccountProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      provider: sso_customer
      guard:
        authenticators:
          - App\Security\SsoAuthCustomer
      logout:
        path: app_logout
  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY  }


