###############################################################################
#                          Generated on .docker.io                          #
###############################################################################
version: "3.1"
services:
  mariadb:
    image: mariadb:10.4
    container_name: cloud-invoicer-mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=pswd
      - MYSQL_DATABASE=cloudinvoicer
      - MYSQL_USER=cloudinvoicer
      - MYSQL_PASSWORD=pswd
    ports:
      - "8083:3306"

  webserver:
    image: nginx:alpine
    container_name: cloud-invoicer-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: .docker/php-fpm
    container_name: cloud-invoicer-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

