parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
  App\Controller\SecurityController:
    arguments:
      $ssoHost: '%env(string:SSO_SERVER_HOST)%'
      $selfHost: '%env(string:SELF_SERVER_HOST)%'

  App\Security\AccountProvider:
    arguments:
      $ssoHost: '%env(string:SSO_SERVER_HOST)%'